Repository hackprot0/json, pull requests merged in 2022-10, with the labels that each got.

#1 Add cmake initializer for clang
  pack-cp.in
Labels: documentation, help wanted, good first issue

#2 Nlohmann activation script in JS
  cmake.in
  nholman-activation.cpp
Labels: documentation, help wanted, hacktoberfest-accepted

#3 Add gcc containerization
  gccc.in
Labels: documentation, help wanted, good first issue, hacktoberfest-accepted

#4 Workspace bazel allocation
  oy-bazel-upgrade.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#5 Random number generator in range of (min,max)
  tests/src/random-gen.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#6 A circular queue util to parse json data
  tests/src/circular-queue-dataparser.cpp
Labels: enhancement, help wanted, hacktoberfest-accepted, hacktoberfest

#7 Testing network connection using socket programming
  tests/client-server/socket-test.py
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#8 A mock server to test socket binding
  tests/client-server/server.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#9 Client to connect to the socket-server
  tests/client-server/client.py
Labels: help wanted, hacktoberfest-accepted, hacktoberfest
